[package]
name = "intro1"
version = "0.1.0"
authors = ["ludwj61 <ludwj61@mail.sunysuffolk.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
